name: Create Release Branch and PR

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select release type"
        required: true
        type: choice
        options:
          - Major
          - Minor
          - Patch
          - Manually Specified
      manual_version:
        description: "Manually specify version number"
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          latest_version=${latest_tag#v}  # Remove 'v' prefix if it exists
          echo "latest_version=${latest_version}" >> $GITHUB_ENV

      - name: Determine new version
        id: determine_version
        run: |
          latest_version=${{ env.latest_version }}
          echo "Current version is ${latest_version}"
          IFS='.' read -r major minor patch <<< "$latest_version"

          case "${{ github.event.inputs.release_type }}" in
            "Major")
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            "Minor")
              minor=$((minor + 1))
              patch=0
              ;;
            "Patch")
              patch=$((patch + 1))
              ;;
            "Manually Specified")
              if [ -z "${{ github.event.inputs.manual_version }}" ]; then
                echo "Error: Manual version number must be provided."
                exit 1
              fi
              new_version="${{ github.event.inputs.manual_version }}"
              ;;
          esac

          if [ "${{ github.event.inputs.release_type }}" != "Manually Specified" ]; then
            new_version="${major}.${minor}.${patch}"
          fi

          echo "new_version=${new_version}" >> $GITHUB_ENV
          echo "New version is ${new_version}"
