name: Create Release Branch and PR

on:
  pull_request:
    branches:
      - "develop"
    types: [opened, reopened, synchronize]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          latest_version=${latest_tag#v}  # Remove 'v' prefix if it exists
          echo "latest_version=${latest_version}" >> $GITHUB_ENV

      - name: Determine new version
        id: determine_version
        run: |
          latest_version=${{ env.latest_version }}
          echo "${current_version}"
