name: Finalize Release

on:
  pull_request:
    branches:
      - "develop"
    types: [opened, reopened, synchronize]

jobs:
  finalize_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Determine release branch and version
        run: |
          # Get the branch name that triggered the workflow
          release_branch="${{ github.ref_name }}"
          echo "${{ github.ref_name }}"
