name: Finalize Release

on:
  workflow_dispatch:
    inputs:
      pr_url:
        description: "The URL of the PR to merge release into main"
        required: true
        type: string

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  finalize_release:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR URL
        id: validate_pr_url
        run: |
          if [[ ! "${{ github.event.inputs.pr_url }}" =~ ^https://github.com/[^/]+/[^/]+/pull/[0-9]+$ ]]; then
            echo "Error: The PR URL '${{ github.event.inputs.pr_url }}' does not match the expected format 'https://github.com/owner/repo/pull/X'."
            exit 1
          fi

      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Extract branch and version
        id: extract_release_info
        run: |
          release_pr_number=$(echo "${{ github.event.inputs.pr_url }}" | grep -oP '\d+$')

          if [[ -z "$release_pr_number" ]]; then
            echo "No PR number found in the URL. Exiting workflow."
            exit 78
          fi

          # Get the PR details to determine the branch
          pr_details=$(gh pr view $release_pr_number --json headRefName -q ".headRefName")

          release_branch="${pr_details}"
          new_version="${release_branch#*/}"

          if [[ ! "$release_branch" =~ ^(release|hotfix)/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Release branch '$release_branch' does not match the expected format 'release/vX.X.X' or 'hotfix/vX.X.X'. Exiting workflow."
            exit 78
          fi

          echo "release_pr_number=$release_pr_number" >> $GITHUB_ENV
          echo "release_branch=$release_branch" >> $GITHUB_ENV
          echo "new_version=$new_version" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge release PR
        run: |
          gh pr merge ${{ env.release_pr_number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag new version
        run: |
          git tag -a "${{ env.new_version }}" -m "Release version ${{ env.new_version }}"
          git push origin "${{ env.new_version }}" -f

      - name: Get Release Notes
        id: get_release_notes
        run: |
          awk '/^## \[${{ env.new_version }}\]/ {flag=1; next} /^## \[/{if (flag) exit} flag {print $0}' CHANGELOG.md >> tmp_changelog.md
          sleep 10

      - name: Create GitHub Release
        run: |
          gh release create "${{ env.new_version }}" \
            --title "${{ env.new_version }}" \
            --notes-file tmp_changelog.md \
            --latest \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR to merge main into develop
        run: |
          pr_url=$(gh pr create \
            --base develop \
            --head main \
            --title "Merge main into develop for release ${{ env.new_version }}" \
            --body "This PR is to merge the main branch into develop after releasing version ${{ env.new_version }}.")

          echo "pr_url=$pr_url" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug PR URL and Extract PR Number
        run: |
          echo "PR URL: ${{ env.pr_url }}"
          pr_number=$(echo "${{ env.pr_url }}" | grep -oP '\d+$')
          echo "Extracted PR Number: $pr_number"

          echo "pr_number=$pr_number" >> $GITHUB_ENV

      - name: Merge PR
        run: |
          gh pr merge ${{ env.pr_number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete release branch
        run: |
          git push origin --delete "${{ env.release_branch }}"
