name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        type: choice
        options:
          - Minor
          - Patch
          - Major
      needs_manual_approval:
        description: "Flag whether or not manual approval is needed before the Production deployment."
        required: true
        type: choice
        options:
          - false
          - true
        default: false

jobs:
  generate_version_number:
    uses: ./.github/workflows/reusable-generate-version-number.yml
    with:
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit

  create_release_branch:
    needs: generate_version_number
    uses: ./.github/workflows/reusable-create-release-branch.yml
    with:
      release_type: ${{ github.event.inputs.release_type }}
      new_version: ${{ needs.generate_version_number.outputs.new_version }}
    secrets: inherit

  update_release_artifacts:
    needs: [generate_version_number, create_release_branch]
    uses: ./.github/workflows/reusable-update-release-artifacts.yml
    with:
      new_version: ${{ needs.generate_version_number.outputs.new_version }}
      current_version: ${{ needs.generate_version_number.outputs.current_version }}
      branch_name: ${{ needs.create_release_branch.outputs.branch_name }}
    secrets: inherit

  create_production_release_pull_request:
    needs: [generate_version_number, create_release_branch]
    uses: ./.github/workflows/reusable-create-pull-request.yml
    with:
      base: main
      head: ${{ needs.create_release_branch.outputs.branch_name }}
      body: "Pull request for ${{ github.event.inputs.release_type }} release ${{ needs.generate_version_number.outputs.new_version }}."
      title: "Release ${{ needs.generate_version_number.outputs.new_version }}"
    secrets: inherit

  manual_approval:
    runs-on: ubuntu-latest
    needs: create_production_release_pull_request
    if: ${{ inputs.needs_manual_approval == 'true' || inputs.release_type == 'Patch' }}
    environment: "Production"
    steps:
      - run: echo "Approved to Prod"

  what_it_do:
    runs-on: ubuntu-latest
    needs: manual_approval
    steps:
      - run: echo "what this do"
