name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release Type"
        required: true
        type: choice
        options:
          - Minor
          - Patch
          - Major

jobs:
  generate_version_number:
    uses: ./.github/workflows/reusable-generate-version-number.yml
    with:
      release_type: ${{ github.event.inputs.release_type }}
    secrets: inherit

  test_version_number:
    runs-on: ubuntu-latest
    needs: generate_version_number
    steps:
      - name: Output the versions
        run: |
          echo "Current version: ${{ needs.generate_version_number.outputs.current_version }}"
          echo "New version: ${{ needs.generate_version_number.outputs.new_version }}"

  create_release_branch:
    needs: generate_version_number
    uses: ./.github/workflows/reusable-create-release-branch.yml
    with:
      release_type: ${{ github.event.inputs.release_type }}
      new_version: ${{ needs.generate_version_number.outputs.new_version }}
    secrets: inherit

  test_create_release_branch:
    runs-on: ubuntu-latest
    needs: create_release_branch
    steps:
      - name: Output the release branch
        run: |
          echo "Release branch: ${{ needs.create_release_branch.outputs.branch_name }}"

  update_release_artifacts:
    needs: [generate_version_number, create_release_branch]
    uses: ./.github/workflows/reusable-update-release-artifacts.yml
    with:
      new_version: ${{ needs.generate_version_number.outputs.new_version }}
      current_version: ${{ needs.generate_version_number.outputs.current_version }}
      branch_name: ${{ needs.create_release_branch.outputs.branch_name }}
    secrets: inherit
